name: website-testing
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      - run: terraform --version
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install ansible
        run: |
          pip3 install -U pip
          pip3 install ansible
      - run: ansible --version